baseURL = 'https://droom.vision/'
languageCode = 'ru'
defaultContentLanguage = 'ru'
title = 'Droomvisioen'
timeZone = 'Europe/Kiev'

[permalinks]
  blog = '/:section/:slug/'
  notes = '/:section/:year/:month/:day/:slug/'
