baseURL = 'https://droom.vision/'
languageCode = 'ru'
defaultContentLanguage = 'ru'
title = 'Droomvisioen'
timeZone = 'Europe/Kiev'
uglyurls = true

[author]
name = "Sasha Wasilewska"

[permalinks]
  blog = '/blog/:slug'
  notes = '/notes/:year/:month/:day/:slug'

[outputs]
  home = ['HTML', 'RSS', 'GEMTEXT']
  section = ['HTML', 'RSS', 'GEMTEXT']
  page = ['HTML', 'GEMTEXT']

[mediaTypes]
  [mediaTypes.'text/gemini']
    suffixes = ['gmi']

[outputFormats]
  [outputFormats.GEMINI]
    name = 'GEMTEXT'
    baseName = 'index'
    isPlainText = true
    isHTML = false
    mediaType = 'text/gemini'
    protocol = 'gemini://'
    permalinkable = true
    path = 'gemini/'
