name: "Build Hugo website"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: "Build Hugo website"
        run: hugo --minify

      - name: "Upload Hugo website"
        uses: actions/upload-artifact@v2
        with:
          name: hugo
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Unpack Hugo website"
        uses: actions/download-artifact@v2
        with:
          name: hugo

      - name: "Deploy Hugo website to InnerEq.org"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CI_DEPLOYER_SSH_ADDRESS_INNEREQ }}
          username: ${{ secrets.CI_DEPLOYER_SSH_USER }}
          key: ${{ secrets.CI_DEPLOYER_SSH_KEY_INNEREQ }}
          port: ${{ secrets.CI_DEPLOYER_SSH_PORT }}
          source: .
          target: /srv/http/droom.vision
          Strip_components: 1
          rm: true
